#!/bin/sh /etc/rc.common
# Copyright (C) 2009-2010 OpenWrt.org

START=99
STOP=15

OLED="python /usr/share/oled/oled.py"

start() {
		
		# 启动 OLED
		nohup $OLED  > /dev/null 2>&1 &

}

stop() {
		# 关闭 OLED
		kill -9 `pidof python /usr/share/oled/oled.py|sed "s/$//g"` 2>/dev/null
}

